[style.description]
bold = false
underline = false

[style.command_name]
bold = false
foreground = "cyan"
underline = false

[style.example_text]
bold = false
foreground = "green"
underline = false

[style.example_code]
bold = false
foreground = "cyan"
underline = false

[style.example_variable]
bold = false
foreground = "cyan"
underline = true

[display]
compact = false
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720
